/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import main.Object.HopDong;
import db.DataAccessObject;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Windows
 */
public class FromClient extends javax.swing.JFrame {
//	public DBConnect db;
    public HopDong hopDong;
    public DataAccessObject db;
    
    int nhanBaoCuoc,banKe,thanhToan;
    
    /**
     * Creates new form FromClient
     */
    public FromClient() {
        db = new DataAccessObject();
        try {
            initComponents();
            ResultSet rs ;
            switch(Instance.xStatus){
                case -1:
                    btnMainAction.setText("Delete");
                    rs = db.getResulSet("select * from ContractsLocal where id = "+Instance.idContract);
                    if(rs.getRow()==0)
                        rs = db.getResulSet("select * from Contracts where id = "+Instance.idContract);
                    FillData(rs);
                    break;
                case 1:
                    btnMainAction.setText("Save");
                    rs = db.getResulSet("select * from ContractsLocal where id = "+Instance.idContract);
                    if(rs.getRow()==0)
                        rs = db.getResulSet("select * from Contracts where id = "+Instance.idContract);
                    FillData(rs);
                    break;
                case 0:
                    btnMainAction.setText("Add");    
                    break;
            }
        } catch (Exception ex) {
            Logger.getLogger(FromClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NhanBaoCuoc = new javax.swing.ButtonGroup();
        NhanBanKe = new javax.swing.ButtonGroup();
        ThanhToan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        tfATenKhachHang = new javax.swing.JTextField();
        tfANguoiDaiDien = new javax.swing.JTextField();
        tfAChucVu = new javax.swing.JTextField();
        tfNamNu = new javax.swing.JTextField();
        tfASoCMND = new javax.swing.JTextField();
        tfANoiCapCMND = new javax.swing.JTextField();
        tfASoHoKhau = new javax.swing.JTextField();
        tfANoiCapSoHoKhau = new javax.swing.JTextField();
        tfASoGiayChungNhanDKDN = new javax.swing.JTextField();
        tfANoiCapGiayChungNhanDKDN = new javax.swing.JTextField();
        tfASoNha = new javax.swing.JTextField();
        tfADuong = new javax.swing.JTextField();
        tfATo = new javax.swing.JTextField();
        tfAPhuong = new javax.swing.JTextField();
        tfATinh = new javax.swing.JTextField();
        tfAQuang = new javax.swing.JTextField();
        tfADienThoai = new javax.swing.JTextField();
        tfAFax = new javax.swing.JTextField();
        tfAEmail = new javax.swing.JTextField();
        tfAMaSoThue = new javax.swing.JTextField();
        dcrANgaySinh = new com.toedter.calendar.JDateChooser();
        dcrANoiCapCMND = new com.toedter.calendar.JDateChooser();
        dcrASoHoKhau = new com.toedter.calendar.JDateChooser();
        dcrAGiayChungNhanDKDN = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfTaiKhoanGianDich1 = new javax.swing.JTextField();
        tfTaiKhoanGianDich2 = new javax.swing.JTextField();
        tfTaiKhoanGianDich3 = new javax.swing.JTextField();
        tfTaiKhoanGianDich4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        rbThanhToan1 = new javax.swing.JRadioButton();
        rbThanhToan2 = new javax.swing.JRadioButton();
        rbThanhToan3 = new javax.swing.JRadioButton();
        rbThanhToan4 = new javax.swing.JRadioButton();
        rbThanhToan5 = new javax.swing.JRadioButton();
        rbThanhToan6 = new javax.swing.JRadioButton();
        rbNhanBaoCuoc6 = new javax.swing.JRadioButton();
        rbNhanBaoCuoc1 = new javax.swing.JRadioButton();
        rbNhanBaoCuoc2 = new javax.swing.JRadioButton();
        rbNhanBaoCuoc3 = new javax.swing.JRadioButton();
        rbNhanBaoCuoc4 = new javax.swing.JRadioButton();
        rbNhanBaoCuoc5 = new javax.swing.JRadioButton();
        NhanBanKe1 = new javax.swing.JRadioButton();
        NhanBanKe2 = new javax.swing.JRadioButton();
        NhanBanKe3 = new javax.swing.JRadioButton();
        NhanBanKe4 = new javax.swing.JRadioButton();
        NhanBanKe5 = new javax.swing.JRadioButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        tfEmailNhanBaoCuoc = new javax.swing.JTextField();
        tfSDTNhanBaoCuoc = new javax.swing.JTextField();
        tfSoTaiKhoan = new javax.swing.JTextField();
        tfNganHang = new javax.swing.JTextField();
        tfChiNhanh = new javax.swing.JTextField();
        tfBaoCuocKhac = new javax.swing.JTextField();
        tfBanKeKhac = new javax.swing.JTextField();
        tfThanhToanKhac = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tfHopDongSo = new javax.swing.JTextField();
        tfMaKhachHang = new javax.swing.JTextField();
        tfMaCH = new javax.swing.JTextField();
        tfHopDongKiTai = new javax.swing.JTextField();
        btnMainAction = new javax.swing.JButton();
        dcrNgayKyHopDong = new com.toedter.calendar.JDateChooser();
        btnClos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hợp đồng số:");

        jLabel3.setText("Mã CH/Đại lý:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("HỢP ĐỒNG CUNG CẤP VÀ SỬ DỤNG DỊCH VỤ");
        jLabel4.setAlignmentX(0.5F);

        jLabel5.setText("Hợp đồng cung cấp và sử dụng dịch vụ viễn thông, truyền hình (dưới đây gọi tắt là “Hợp đồng”) được ký kết ngày");

        jLabel6.setText("Mã KH:");

        jLabel8.setText("Tại");

        jLabel10.setText("Tên Khách hàng/chủ Hợp đồng: Tên cơ quan/Tổ chức/Cá nhân (viết hoa):");

        jLabel11.setText("Người đại diện (áp dụng đối với cơ quan/tổ chức):");

        jLabel12.setText("Chức vụ:");

        jLabel13.setText("Ngày sinh:");

        jLabel14.setText("Nam/nữ:");

        jLabel15.setText("Số CMND/Hộ chiếu:");

        jLabel16.setText("Nơi cấp:");

        jLabel17.setText("Ngày cấp:");

        jLabel18.setText("Số hộ khẩu/Giấy tờ khác:");

        jLabel19.setText("Nơi cấp:");

        jLabel20.setText("Ngày cấp:");

        jLabel21.setText("Số Giấy Chứng nhận ĐKDN/Quyết định thành lập/Giấy phép thành lập:");

        jLabel22.setText("Nơi cấp:");

        jLabel23.setText("Ngày cấp:");

        jLabel24.setText("Địa chỉ theo CMND/Giấy Chứng nhận ĐKDN/Quyết định thành lập/Giấy phép thành lập:");

        jLabel25.setText("Số nhà:");

        jLabel26.setText("Đường:");

        jLabel27.setText("Tổ");

        jLabel28.setText("Phường/xã");

        jLabel29.setText("Quận/Huyện");

        jLabel30.setText("Tỉnh/TP");

        jLabel31.setText("Điện thoại:");

        jLabel32.setText(" Fax:");

        jLabel33.setText("Email:");

        jLabel34.setText("Mã số thuế:");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setText("BÊN SỬ DỤNG DỊCH VỤ VIỄN THÔNG (Gọi tắt là “Bên A”)");

        tfNamNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamNuActionPerformed(evt);
            }
        });

        tfAEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfANoiCapGiayChungNhanDKDN, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel24)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfAChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcrANgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfASoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfANoiCapCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfASoGiayChungNhanDKDN))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfASoHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfANoiCapSoHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dcrAGiayChungNhanDKDN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dcrASoHoKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel14)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dcrANoiCapCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfNamNu, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfATenKhachHang)
                                .addComponent(tfANguoiDaiDien, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel34)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfAMaSoThue))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel31)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfADienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel32)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfAFax, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel33)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfAEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfAQuang, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfASoNha, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfADuong, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfATo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel28)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfAPhuong, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel30)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfATinh))))))
                .addGap(357, 357, 357))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfATenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfANguoiDaiDien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(tfAChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(tfNamNu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(dcrANgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tfASoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(tfANoiCapCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addComponent(dcrANoiCapCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20)
                        .addComponent(tfASoHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfANoiCapSoHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dcrASoHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(tfASoGiayChungNhanDKDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(tfANoiCapGiayChungNhanDKDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel24))
                    .addComponent(dcrAGiayChungNhanDKDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(tfASoNha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfADuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(tfAQuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(tfATo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAPhuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(tfATinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(tfADienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(tfAMaSoThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bên A", jPanel1);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setText("BÊN CUNG CẤP DỊCH VỤ : TỔNG CÔNG TY VIỄN THÔNG VIETTEL - CHI NHÁNH TẬP ĐOÀN "); // NOI18N

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setText("VIỄN THÔNG QUÂN ĐỘI (Gọi tắt là “Bên B”)");

        jLabel38.setText("Người đại diện                        : Hoàng Sơn - Tổng Giám đốc Tổng Công ty Viễn thông Viettel (Viettel Telecom)");

        jLabel39.setText("Địa chỉ                                    : Số 1 - Giang Văn Minh - Phường Kim Mã - Quận Ba Đình - Thành phố Hà Nội.");

        jLabel40.setText("Điện thoại                              : 18008098 (Dịch vụ di động)/18008119 (Dịch vụ cố định)                Fax: 04 62660446");

        jLabel41.setText("Mã số thuế                             : 0100109106 - 011");

        jLabel42.setText("Đơn vị thụ hưởng                   : Tập đoàn Viễn thông Quân đội");

        jLabel2.setText("Tài khoản giao dịch                 :");

        tfTaiKhoanGianDich1.setEditable(false);

        tfTaiKhoanGianDich2.setEditable(false);

        tfTaiKhoanGianDich3.setEditable(false);

        tfTaiKhoanGianDich4.setEditable(false);

        jLabel7.setText("tại Ngân hàng TMCP Quân Đội - Chi nhánh Điện Biên Phủ");

        jLabel9.setText("tại Ngân hàng TMCP Đầu tư và Phát triển Việt Nam - Sở Giao Dịch 1");

        jLabel47.setText("tại Ngân Hàng NN&PTNN - Chi nhánh Láng Hạ");

        jLabel48.setText("tại Ngân hàng Bưu Điện Liên Việt, Hội sở");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel38))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel39))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel40))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel41))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel42))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfTaiKhoanGianDich2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTaiKhoanGianDich1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfTaiKhoanGianDich3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTaiKhoanGianDich4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfTaiKhoanGianDich1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTaiKhoanGianDich2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTaiKhoanGianDich3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTaiKhoanGianDich4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bên B", jPanel2);

        jLabel43.setText("Bên B đồng ý cung cấp và Bên A đồng ý sử dụng dịch vụ như sau:");

        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setWheelScrollingEnabled(false);

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {1, null, null, null, null, null, null, null},
                {2, null, null, null, null, null, null, null},
                {3, null, null, null, null, null, null, null},
                {4, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Loại dịch vụ","Địa chỉ lắp đặt","Số điện thoại/Tên truy cập","Gói cước/Tốc độ", "Phí hòa mạng/lắp đặt","Ghi chú"
            }
        ));
        jScrollPane1.setViewportView(tblDichVu);

        ThanhToan.add(rbThanhToan1);
        rbThanhToan1.setText("Ủy nhiệm thu qua ngân hàng");
        rbThanhToan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbThanhToan1ActionPerformed(evt);
            }
        });

        ThanhToan.add(rbThanhToan2);
        rbThanhToan2.setText("Ủy nhiệm chi qua ngân hàng");
        rbThanhToan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbThanhToan2ActionPerformed(evt);
            }
        });

        ThanhToan.add(rbThanhToan3);
        rbThanhToan3.setText(" Tại cửa hàng trực tiếp của Viettel");
        rbThanhToan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbThanhToan3ActionPerformed(evt);
            }
        });

        ThanhToan.add(rbThanhToan4);
        rbThanhToan4.setText(" Thanh toán qua Thương mại điện tử");
        rbThanhToan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbThanhToan4ActionPerformed(evt);
            }
        });

        ThanhToan.add(rbThanhToan5);
        rbThanhToan5.setText("Thanh toán qua thẻ cào (Phương thức này Viettel không cung cấp hóa đơn)");
        rbThanhToan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbThanhToan5ActionPerformed(evt);
            }
        });

        ThanhToan.add(rbThanhToan6);
        rbThanhToan6.setText("Khác");
        rbThanhToan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbThanhToan6ActionPerformed(evt);
            }
        });

        NhanBaoCuoc.add(rbNhanBaoCuoc6);
        rbNhanBaoCuoc6.setText("Khác");
        rbNhanBaoCuoc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNhanBaoCuoc6ActionPerformed(evt);
            }
        });

        NhanBaoCuoc.add(rbNhanBaoCuoc1);
        rbNhanBaoCuoc1.setText(" Nhận trực tiếp tại điểm giao dịch của Viettel");
        rbNhanBaoCuoc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNhanBaoCuoc1ActionPerformed(evt);
            }
        });

        NhanBaoCuoc.add(rbNhanBaoCuoc2);
        rbNhanBaoCuoc2.setText("Qua thư điện tử");
        rbNhanBaoCuoc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNhanBaoCuoc2ActionPerformed(evt);
            }
        });

        NhanBaoCuoc.add(rbNhanBaoCuoc3);
        rbNhanBaoCuoc3.setText("Qua tin nhắn SMS");
        rbNhanBaoCuoc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNhanBaoCuoc3ActionPerformed(evt);
            }
        });

        NhanBaoCuoc.add(rbNhanBaoCuoc4);
        rbNhanBaoCuoc4.setText(" Qua cổng thông tin điện tử của Viettel");
        rbNhanBaoCuoc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNhanBaoCuoc4ActionPerformed(evt);
            }
        });

        NhanBaoCuoc.add(rbNhanBaoCuoc5);
        rbNhanBaoCuoc5.setText("Không nhận");
        rbNhanBaoCuoc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNhanBaoCuoc5ActionPerformed(evt);
            }
        });

        NhanBanKe.add(NhanBanKe1);
        NhanBanKe1.setText(" Nhận trực tiếp tại điểm giao dịch của Viettel");
        NhanBanKe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhanBanKe1ActionPerformed(evt);
            }
        });

        NhanBanKe.add(NhanBanKe2);
        NhanBanKe2.setText(" Qua thư điện tử");
        NhanBanKe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhanBanKe2ActionPerformed(evt);
            }
        });

        NhanBanKe.add(NhanBanKe3);
        NhanBanKe3.setText("Qua cổng thông tin điện tử của Viettel");
        NhanBanKe3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhanBanKe3ActionPerformed(evt);
            }
        });

        NhanBanKe.add(NhanBanKe4);
        NhanBanKe4.setText("Không nhận");
        NhanBanKe4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhanBanKe4ActionPerformed(evt);
            }
        });

        NhanBanKe.add(NhanBanKe5);
        NhanBanKe5.setText("Khác");
        NhanBanKe5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhanBanKe5ActionPerformed(evt);
            }
        });

        jLabel44.setText("Hình thức nhận thông báo cước");

        jLabel45.setText("Hình thức nhận bản kê chi tiết");

        jLabel46.setText("Hình thức thanh toán");

        jLabel49.setText("Email nhận Thông báo cước/Chi tiết cước:");

        jLabel50.setText("Số ĐT nhận Thông báo cước");

        jLabel51.setText("Số Tài khoản:");

        jLabel52.setText("Ngân hàng:");

        jLabel53.setText("Chi nhánh:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rbNhanBaoCuoc6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfBaoCuocKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbNhanBaoCuoc1)
                                            .addComponent(rbNhanBaoCuoc2)
                                            .addComponent(rbNhanBaoCuoc3)
                                            .addComponent(rbNhanBaoCuoc4)
                                            .addComponent(rbNhanBaoCuoc5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NhanBanKe1)
                                            .addComponent(NhanBanKe2)
                                            .addComponent(NhanBanKe3)
                                            .addComponent(NhanBanKe4)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(NhanBanKe5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfBanKeKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel45))
                                        .addGap(72, 72, 72)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbThanhToan1)
                                    .addComponent(rbThanhToan2)
                                    .addComponent(rbThanhToan3)
                                    .addComponent(rbThanhToan4)
                                    .addComponent(rbThanhToan5)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rbThanhToan6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfThanhToanKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel46)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addGap(97, 97, 97)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel50)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfSDTNhanBaoCuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel49)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfEmailNhanBaoCuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel51)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfSoTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel53)
                                            .addComponent(jLabel52))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNganHang, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfChiNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(NhanBanKe2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NhanBanKe3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NhanBanKe4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NhanBanKe5)
                            .addComponent(tfBanKeKhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbNhanBaoCuoc1)
                            .addComponent(NhanBanKe1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbNhanBaoCuoc2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbNhanBaoCuoc3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbNhanBaoCuoc4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbNhanBaoCuoc5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbNhanBaoCuoc6)
                            .addComponent(tfBaoCuocKhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbThanhToan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbThanhToan2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbThanhToan3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbThanhToan4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbThanhToan5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbThanhToan6)
                            .addComponent(tfThanhToanKhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(jLabel51)
                    .addComponent(tfEmailNhanBaoCuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSoTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(jLabel52)
                    .addComponent(tfSDTNhanBaoCuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNganHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(tfChiNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dịch vụ sử dụng", jPanel3);

        jButton1.setText("Load");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfMaCH.setEditable(false);

        btnMainAction.setText("save");
        btnMainAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionActionPerformed(evt);
            }
        });

        btnClos.setText("Close");
        btnClos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfHopDongSo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfMaCH))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(29, 29, 29)
                                    .addComponent(dcrNgayKyHopDong, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                                .addComponent(tfHopDongKiTai, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButton1)
                        .addGap(30, 30, 30)
                        .addComponent(btnMainAction)
                        .addGap(203, 203, 203)
                        .addComponent(btnClos)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(tfHopDongSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMaCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(dcrNgayKyHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfHopDongKiTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnMainAction)
                    .addComponent(btnClos))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbThanhToan5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbThanhToan5ActionPerformed
        // TODO add your handling code here:
        tfThanhToanKhac.setEditable(false);
        tfThanhToanKhac.setText("");
        thanhToan = 5;
    }//GEN-LAST:event_rbThanhToan5ActionPerformed

    private void rbThanhToan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbThanhToan6ActionPerformed
        // TODO add your handling code here:
        tfThanhToanKhac.setEditable(true);
        thanhToan = 6;
    }//GEN-LAST:event_rbThanhToan6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfNamNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamNuActionPerformed

    private void btnMainActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionActionPerformed
        try {
            String action = "Insert";
//                db = new DataAccessObject();
//            ResultSet rs = db.getAllFromTable("ContractsLocal");
//            ResultSet rs = db.getResulSet("select * from ContractsLocal where SoHopDong = "+hopDong.SoHopDong+"");
//            if(rs.next())
//                action = "Update";
//            else
//                action = "Insert";
            LuuHopDong();
            hopDong.xStatus =String.valueOf(Instance.xStatus);
            String sql = action+" into ContractsLocal (SoHopDong, MaKhachHang, MaDaiLy, NgayDKHopDong, DiaDiemDKHopDong,"
                    + " TenKhachHang, NguoiDaiDien, ChucVu, NgaySinh, GioiTinh, CMND, NoiCapCMND, NgayCapCMND, SoHoKhau,"
                    + " NoiCapSoHoKhau, NgayCapSoHoKhau, SoGiayChungNhanDKDN, NoiCapDKDN, NgayCapDKDN, SoNha, Duong, xTo,"
                    + " PhuongXa, QuanHuyen, TinhTp, SDTKhachHang, Email, MaSoThueKhachHang, DichVuID, NhanBaoCuoc,"
                    + " NhanBaoCuocKhac, NhanBanKe, NhanBanKeKhac, EmailNhanBaoCuoc, SDTNhanBaoCuoc, ThanhToan, "
                    + "ThanhToanKhac, SoTaiKhoanThanhToan, NganHang, ChiNhanh, xStatus)"
                    + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";
            db.executeSQLwithParams(sql, DataAccessObject.MODE_UPDATE.SMALL_UPDATE,
                    hopDong.SoHopDong, hopDong.MaKhachHang, hopDong.MaDaiLy, hopDong.NgayDKHopDong, hopDong.DiaDiemDKHopDong,
                    hopDong.TenKhachHang, hopDong.NguoiDaiDien, hopDong.ChucVu, hopDong.NgaySinh, hopDong.GioiTinh, hopDong.CMND, hopDong.NoiCapCMND, hopDong.NgayCapCMND, hopDong.SoHoKhau,
                    hopDong.NoiCapSoHoKhau, hopDong.NgayCapSoHoKhau, hopDong.SoGiayChungNhanDKDN, hopDong.NoiCapDKDN, hopDong.NgayCapDKDN, hopDong.SoNha, hopDong.Duong, hopDong.xTo,
                    hopDong.PhuongXa, hopDong.QuanHuyen, hopDong.TinhTp, hopDong.SDTKhachHang, hopDong.Email, hopDong.MaSoThueKhachHang, hopDong.DichVuID, hopDong.NhanBaoCuoc,
                    hopDong.NhanBaoCuocKhac, hopDong.NhanBanKe, hopDong.NhanBanKeKhac, hopDong.EmailNhanBaoCuoc, hopDong.SDTNhanBaoCuoc, hopDong.ThanhToan,
                    hopDong.ThanhToanKhac, hopDong.SoTaiKhoanThanhToan, hopDong.NganHang, hopDong.ChiNhanh, hopDong.xStatus
            );
            
        } catch (SQLException ex) {
            Logger.getLogger(FromClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FromClient.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            setFocusable(false);
            setEnabled(false);
            setVisible(false);
        }
    }//GEN-LAST:event_btnMainActionActionPerformed

    private void tfAEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAEmailActionPerformed

    private void rbNhanBaoCuoc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNhanBaoCuoc1ActionPerformed
        // TODO add your handling code here:
        tfBaoCuocKhac.setEditable(true);
        nhanBaoCuoc = 1;        tfBaoCuocKhac.setText("");

    }//GEN-LAST:event_rbNhanBaoCuoc1ActionPerformed

    private void rbNhanBaoCuoc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNhanBaoCuoc2ActionPerformed
        // TODO add your handling code here:
         tfBaoCuocKhac.setEditable(true);
       nhanBaoCuoc=2;        tfBaoCuocKhac.setText("");

    }//GEN-LAST:event_rbNhanBaoCuoc2ActionPerformed

    private void rbNhanBaoCuoc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNhanBaoCuoc3ActionPerformed
        // TODO add your handling code here:
        tfBaoCuocKhac.setEditable(true);
        nhanBaoCuoc =3;        tfBaoCuocKhac.setText("");

    }//GEN-LAST:event_rbNhanBaoCuoc3ActionPerformed

    private void rbNhanBaoCuoc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNhanBaoCuoc4ActionPerformed
        // TODO add your handling code here:
          tfBaoCuocKhac.setEditable(true);
      nhanBaoCuoc = 4;        tfBaoCuocKhac.setText("");

    }//GEN-LAST:event_rbNhanBaoCuoc4ActionPerformed

    private void rbNhanBaoCuoc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNhanBaoCuoc5ActionPerformed
        // TODO add your handling code here:
        nhanBaoCuoc = 5;
        tfBaoCuocKhac.setEditable(true);
        tfBaoCuocKhac.setText("");
    }//GEN-LAST:event_rbNhanBaoCuoc5ActionPerformed

    private void rbNhanBaoCuoc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNhanBaoCuoc6ActionPerformed
        // TODO add your handling code here:
        nhanBaoCuoc = 6;
        tfBaoCuocKhac.setEditable(false);
    }//GEN-LAST:event_rbNhanBaoCuoc6ActionPerformed

    private void NhanBanKe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhanBanKe1ActionPerformed
        // TODO add your handling code here:
        banKe= 1;
        tfBanKeKhac.setEditable(false);
                tfBanKeKhac.setText("");

    }//GEN-LAST:event_NhanBanKe1ActionPerformed

    private void NhanBanKe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhanBanKe2ActionPerformed
        // TODO add your handling code here:
        banKe= 2;
                tfBanKeKhac.setEditable(false);
        tfBanKeKhac.setText("");

    }//GEN-LAST:event_NhanBanKe2ActionPerformed

    private void NhanBanKe3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhanBanKe3ActionPerformed
        // TODO add your handling code here:
        banKe= 3;        tfBanKeKhac.setEditable(false);
        tfBanKeKhac.setText("");

    }//GEN-LAST:event_NhanBanKe3ActionPerformed

    private void NhanBanKe4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhanBanKe4ActionPerformed
        // TODO add your handling code here:
        banKe= 4;         tfBanKeKhac.setEditable(false);
        tfBanKeKhac.setText("");

    }//GEN-LAST:event_NhanBanKe4ActionPerformed

    private void NhanBanKe5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhanBanKe5ActionPerformed
        // TODO add your handling code here:
        banKe= 5;        tfBanKeKhac.setEditable(true);
    }//GEN-LAST:event_NhanBanKe5ActionPerformed

    private void rbThanhToan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbThanhToan1ActionPerformed
        // TODO add your handling code here:
        thanhToan = 1;
        tfThanhToanKhac.setEditable(false);
        tfThanhToanKhac.setText("");
    }//GEN-LAST:event_rbThanhToan1ActionPerformed

    private void rbThanhToan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbThanhToan2ActionPerformed
        // TODO add your handling code here:
        tfThanhToanKhac.setEditable(false);
        tfThanhToanKhac.setText("");
        thanhToan = 2;
    }//GEN-LAST:event_rbThanhToan2ActionPerformed

    private void rbThanhToan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbThanhToan3ActionPerformed
        // TODO add your handling code here:
        tfThanhToanKhac.setEditable(false);
        tfThanhToanKhac.setText("");
        thanhToan = 3;
    }//GEN-LAST:event_rbThanhToan3ActionPerformed

    private void rbThanhToan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbThanhToan4ActionPerformed
        // TODO add your handling code here:
         tfThanhToanKhac.setEditable(false);
        tfThanhToanKhac.setText("");
       thanhToan = 4;
    }//GEN-LAST:event_rbThanhToan4ActionPerformed

    private void btnClosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClosActionPerformed
        // TODO add your handling code here:
        setFocusable(false);
        setEnabled(false);
        setVisible(false);
    }//GEN-LAST:event_btnClosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromClient().setVisible(true);
            }
        });
    }
    
    private void CreateDB(){
        db = new DataAccessObject();
    }
    
    private void FillData(ResultSet rs){
        try {
            rs.next(); 
            tfHopDongSo.setText(rs.getString(2));
            tfMaKhachHang.setText(rs.getString(3));
            tfMaCH.setText(rs.getString(4));
            
            tfHopDongKiTai.setText(rs.getString(6));
            tfATenKhachHang.setText(rs.getString(7));
            tfANguoiDaiDien.setText(rs.getString(8));
            tfAChucVu.setText(rs.getString(9)); 

            tfNamNu.setText(rs.getString(11));
            tfASoCMND.setText(rs.getString(12));
            tfANoiCapCMND.setText(rs.getString(13));
            tfASoHoKhau.setText(rs.getString(15));
            tfANoiCapSoHoKhau.setText(rs.getString(16));
            tfASoGiayChungNhanDKDN.setText(rs.getString(18));
            tfANoiCapGiayChungNhanDKDN.setText(rs.getString(19));
            
            DateFormat formatter = new SimpleDateFormat("mm/dd/yy");
            try {
                dcrNgayKyHopDong.setDate((Date) formatter.parse(rs.getString(5)));
                dcrANgaySinh.setDate((Date) formatter.parse(rs.getString(10)));
                dcrANoiCapCMND.setDate((Date) formatter.parse(rs.getString(14)));
                dcrASoHoKhau.setDate((Date) formatter.parse(rs.getString(17)));
                dcrAGiayChungNhanDKDN.setDate((Date) formatter.parse(rs.getString(20)));
            } catch (ParseException e) {
              e.printStackTrace();
            } 
            
            tfASoNha.setText(rs.getString(21));
            tfADuong.setText(rs.getString(22));
            tfATo.setText(rs.getString(23));
            tfAPhuong.setText(rs.getString(24));
            tfAQuang.setText(rs.getString(25));
            tfATinh.setText(rs.getString(26));
            tfADienThoai.setText(rs.getString(27));
            tfAFax.setText(rs.getString(27));
            tfAEmail.setText(rs.getString(28));
            tfAMaSoThue.setText(rs.getString(29));
            
            int nhanBaoCuoc = Integer.parseInt(rs.getString(31));
            int nhanBanKe = Integer.parseInt(rs.getString(33));
            int thanhToan = Integer.parseInt(rs.getString(37));
            
            switch(nhanBaoCuoc){
                case 1:
                    rbNhanBaoCuoc1.doClick();
                    break;
                case 2:
                    rbNhanBaoCuoc2.doClick();
                    break;
                case 3:
                    rbNhanBaoCuoc3.doClick();
                    break;
                case 4:
                    rbNhanBaoCuoc4.doClick();
                    break;
                case 5:
                    rbNhanBaoCuoc5.doClick();
                    break;
                case 6:
                    rbNhanBaoCuoc6.doClick();
                    break;
            }
            
            switch(nhanBanKe){
                case 1:
                    NhanBanKe1.doClick();
                    break;
                case 2:
                    NhanBanKe2.doClick();
                    break;
                case 3:
                    NhanBanKe3.doClick();
                    break;
                case 4:
                    NhanBanKe4.doClick();
                    break;
                case 5:
                    NhanBanKe5.doClick();
                    break;
            }
            
            switch(thanhToan){
                case 1:
                    rbThanhToan1.doClick();
                    break;
                case 2:
                    rbThanhToan2.doClick();
                    break;
                case 3:
                    rbThanhToan3.doClick();
                    break;
                case 4:
                    rbThanhToan4.doClick();
                    break;
                case 5:
                    rbThanhToan5.doClick();
                    break;
                case 6:
                    rbThanhToan6.doClick();
                    break;
            }
            ResultSet soTk = db.getResulSet("Select * from Agents where id = "+ Instance.agentID);

            while(soTk.next()){
                tfMaCH.setText(soTk.getString(2));
                tfTaiKhoanGianDich1.setText(soTk.getString(3));
                tfTaiKhoanGianDich2.setText(soTk.getString(4));
                tfTaiKhoanGianDich3.setText(soTk.getString(5));
                tfTaiKhoanGianDich4.setText(soTk.getString(6));
            }
            
            tfEmailNhanBaoCuoc.setText(rs.getString(35));
            tfSDTNhanBaoCuoc.setText(rs.getString(36));
            tfSoTaiKhoan.setText(rs.getString(39));
            tfNganHang.setText(rs.getString(40));
            tfChiNhanh.setText(rs.getString(41));
            
            int service = rs.getInt("DichVuID");
            
            rs = db.getResulSet("select * from Services where id = "+ service);
            
            while(rs.next()){
                String loadDichVu,diaChiLapDat,sdtLapDat,GoiCuoc,phiHoaMang,ghiChu;
                loadDichVu = rs.getString(2);
                diaChiLapDat = rs.getString(3);
                sdtLapDat = rs.getString(4);
                GoiCuoc = rs.getString(5);
                phiHoaMang = rs.getString(6);
                ghiChu = rs.getString(7);
                tblDichVu.setValueAt(loadDichVu, 0,1);
                tblDichVu.setValueAt(diaChiLapDat, 0,2);
                tblDichVu.setValueAt(sdtLapDat, 0,3);
                tblDichVu.setValueAt(GoiCuoc, 0,4);
                tblDichVu.setValueAt(phiHoaMang, 0,5);
                tblDichVu.setValueAt(ghiChu,0,6);
            }
        } 
        catch (Exception ex) {
            Logger.getLogger(FromClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void LuuHopDong(){
        hopDong =new HopDong();
        hopDong.SoHopDong= tfHopDongSo.getText();
        hopDong.MaKhachHang=    tfMaKhachHang.getText();
        hopDong.MaDaiLy =   tfMaCH.getText();
        hopDong.NgayDKHopDong=   dcrNgayKyHopDong.getDate().toString();
        hopDong.DiaDiemDKHopDong =     tfHopDongKiTai.getText();
        hopDong.TenKhachHang =     tfATenKhachHang.getText();
        hopDong.NguoiDaiDien=    tfANguoiDaiDien.getText();
        hopDong.ChucVu =    tfAChucVu.getText();
        hopDong.NgaySinh = dcrANgaySinh.getDate().toString();
        hopDong.GioiTinh =     tfNamNu.getText();
        hopDong.CMND =    tfASoCMND.getText();
        hopDong.NoiCapCMND =   tfANoiCapCMND.getText();
        hopDong.NgayCapCMND =   dcrANoiCapCMND.getDate().toString();
        hopDong.SoHoKhau =    tfASoHoKhau.getText();
        hopDong.NoiCapSoHoKhau =   tfANoiCapSoHoKhau.getText();
        hopDong.NgayCapSoHoKhau=   dcrASoHoKhau.getDate().toString();
        hopDong.SoGiayChungNhanDKDN=     tfASoGiayChungNhanDKDN.getText();
        hopDong.NoiCapDKDN =   tfANoiCapGiayChungNhanDKDN.getText();
        hopDong.NgayCapDKDN=   dcrAGiayChungNhanDKDN.getDate().toString();
        hopDong.SoNha =   tfASoNha.getText();
        hopDong.Duong =     tfADuong.getText();
        hopDong.xTo =    tfATo.getText();
        hopDong.PhuongXa =    tfAPhuong.getText();
        hopDong.QuanHuyen=   tfAQuang.getText();
        hopDong.TinhTp =    tfATinh.getText();
        hopDong.SDTKhachHang =    tfADienThoai.getText();
        hopDong.Email =     tfAEmail.getText();
        hopDong.MaSoThueKhachHang =    tfAMaSoThue.getText();
        //TODO: ADD DICH VU ID
        hopDong.NhanBaoCuoc =String.valueOf(nhanBaoCuoc);
        if(nhanBaoCuoc == 6)
            hopDong.NhanBaoCuocKhac = tfBaoCuocKhac.getText();
        else 
            hopDong.NhanBaoCuocKhac= "";
        hopDong.NhanBanKe = String.valueOf(banKe);
        if(banKe == 5)
            hopDong.NhanBanKeKhac = tfBanKeKhac.getText();
        else 
            hopDong.NhanBanKeKhac= "";  
        hopDong.ThanhToan = String.valueOf(thanhToan);
        if(thanhToan == 6)
            hopDong.ThanhToanKhac = tfThanhToanKhac.getText();
        else 
            hopDong.ThanhToanKhac = "";
        hopDong.EmailNhanBaoCuoc = tfEmailNhanBaoCuoc.getText();
        hopDong.SDTNhanBaoCuoc = tfSDTNhanBaoCuoc.getText();
        hopDong.SoTaiKhoanThanhToan = tfSoTaiKhoan.getText();
        hopDong.NganHang = tfNganHang.getText();
        hopDong.ChiNhanh = tfChiNhanh.getText();
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup NhanBanKe;
    private javax.swing.JRadioButton NhanBanKe1;
    private javax.swing.JRadioButton NhanBanKe2;
    private javax.swing.JRadioButton NhanBanKe3;
    private javax.swing.JRadioButton NhanBanKe4;
    private javax.swing.JRadioButton NhanBanKe5;
    private javax.swing.ButtonGroup NhanBaoCuoc;
    private javax.swing.ButtonGroup ThanhToan;
    private javax.swing.JButton btnClos;
    private javax.swing.JButton btnMainAction;
    private com.toedter.calendar.JDateChooser dcrAGiayChungNhanDKDN;
    private com.toedter.calendar.JDateChooser dcrANgaySinh;
    private com.toedter.calendar.JDateChooser dcrANoiCapCMND;
    private com.toedter.calendar.JDateChooser dcrASoHoKhau;
    private com.toedter.calendar.JDateChooser dcrNgayKyHopDong;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rbNhanBaoCuoc1;
    private javax.swing.JRadioButton rbNhanBaoCuoc2;
    private javax.swing.JRadioButton rbNhanBaoCuoc3;
    private javax.swing.JRadioButton rbNhanBaoCuoc4;
    private javax.swing.JRadioButton rbNhanBaoCuoc5;
    private javax.swing.JRadioButton rbNhanBaoCuoc6;
    private javax.swing.JRadioButton rbThanhToan1;
    private javax.swing.JRadioButton rbThanhToan2;
    private javax.swing.JRadioButton rbThanhToan3;
    private javax.swing.JRadioButton rbThanhToan4;
    private javax.swing.JRadioButton rbThanhToan5;
    private javax.swing.JRadioButton rbThanhToan6;
    public javax.swing.JTable tblDichVu;
    private javax.swing.JTextField tfAChucVu;
    private javax.swing.JTextField tfADienThoai;
    private javax.swing.JTextField tfADuong;
    private javax.swing.JTextField tfAEmail;
    private javax.swing.JTextField tfAFax;
    private javax.swing.JTextField tfAMaSoThue;
    private javax.swing.JTextField tfANguoiDaiDien;
    private javax.swing.JTextField tfANoiCapCMND;
    private javax.swing.JTextField tfANoiCapGiayChungNhanDKDN;
    private javax.swing.JTextField tfANoiCapSoHoKhau;
    private javax.swing.JTextField tfAPhuong;
    private javax.swing.JTextField tfAQuang;
    private javax.swing.JTextField tfASoCMND;
    private javax.swing.JTextField tfASoGiayChungNhanDKDN;
    private javax.swing.JTextField tfASoHoKhau;
    private javax.swing.JTextField tfASoNha;
    private javax.swing.JTextField tfATenKhachHang;
    private javax.swing.JTextField tfATinh;
    private javax.swing.JTextField tfATo;
    private javax.swing.JTextField tfBanKeKhac;
    private javax.swing.JTextField tfBaoCuocKhac;
    private javax.swing.JTextField tfChiNhanh;
    private javax.swing.JTextField tfEmailNhanBaoCuoc;
    private javax.swing.JTextField tfHopDongKiTai;
    private javax.swing.JTextField tfHopDongSo;
    private javax.swing.JTextField tfMaCH;
    private javax.swing.JTextField tfMaKhachHang;
    private javax.swing.JTextField tfNamNu;
    private javax.swing.JTextField tfNganHang;
    private javax.swing.JTextField tfSDTNhanBaoCuoc;
    private javax.swing.JTextField tfSoTaiKhoan;
    private javax.swing.JTextField tfTaiKhoanGianDich1;
    private javax.swing.JTextField tfTaiKhoanGianDich2;
    private javax.swing.JTextField tfTaiKhoanGianDich3;
    private javax.swing.JTextField tfTaiKhoanGianDich4;
    private javax.swing.JTextField tfThanhToanKhac;
    // End of variables declaration//GEN-END:variables
}
