package main.Object;

public class HopDong{
      public String id = "-1";
      public String SoHopDong = "" ;
      public String MaKhachHang= "" ;
      public String MaDaiLy = "" ;
      public String NgayDKHopDong = "" ;
      public String DiaDiemDKHopDong = "" ;
      public String TenKhachHang= "" ;
      public String NguoiDaiDien = "" ;
      public String ChucVu = "" ;
      public String NgaySinh = "" ;
      public String GioiTinh = "" ;
      public String CMND = "" ;
      public String NoiCapCMND = "" ;
      public String NgayCapCMND = "" ;
      public String SoHoKhau = "" ;
      public String NoiCapSoHoKhau = "" ;
      public String NgayCapSoHoKhau = "" ;
      public String SoGiayChungNhanDKDN = "" ;
      public String NoiCapDKDN = "" ;
      public String NgayCapDKDN = "" ;
      public String SoNha = "" ;
      public String Duong = "" ;
      public String xTo = "" ;
      public String PhuongXa = "" ;
      public String QuanHuyen = "" ;
      public String TinhTp = "" ;
      public String SDTKhachHang = "" ;
      public String Email = "" ;
      public String MaSoThueKhachHang = "" ;
      public String DichVuID = "" ;
      public String NhanBaoCuoc = "" ;
      public String NhanBaoCuocKhac = "" ;
      public String NhanBanKe = "" ;
      public String NhanBanKeKhac = "" ;
      public String EmailNhanBaoCuoc = "" ;
      public String SDTNhanBaoCuoc = "" ;
      public String ThanhToan = "" ;
      public String ThanhToanKhac = "" ;
      public String SoTaiKhoanThanhToan = "" ;
      public String NganHang = "" ;
      public String ChiNhanh = "" ;
      public String xStatus= "" ;
}
